MCU = STM32F401
BOARD = BLACKPILL_STM32_F401

BOOTLOADER = tinyuf2

BOOTMAGIC_ENABLE = yes      
MOUSEKEY_ENABLE = no       
EXTRAKEY_ENABLE = yes      
NKRO_ENABLE = yes           

CONSOLE_ENABLE = no        
COMMAND_ENABLE = no        
BACKLIGHT_ENABLE = no      
RGBLIGHT_ENABLE = no        
AUDIO_ENABLE = no           

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = IS31FL3741

OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE 
